#!/bin/bash

# Detect whether using net-tools --> ifconfig
# Or iproute2 --> ip
if [ "$(which ip)" != '' ];
then
	IPTOOL='ip a'
elif [ "$(which ifconfig)" != '' ];
then
	IPTOOL='ifconfig'
else
	echo "error: cannot find either ifconfig or ip commands"
	exit
fi

# Print IP addresses reported by IPTOOL
case "$1" in
	'-4')		$IPTOOL|awk '/inet\s/{print $2}' ;;
	'-6')		$IPTOOL|awk '/inet6/{print $2}' ;;
	'--help')	;&
	'-h')		echo "usage: getip [-4|-6] [--help|-h]" ;;
	'')			$IPTOOL|awk '/inet/{print $2}' ;;
	*)			echo "error: unknown option '$1'";;
esac
